# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rasha-D' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rasha-D
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Storage'
pod 'SDWebImage', '~> 5.0'

  target 'Rasha-DTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rasha-DUITests' do
    # Pods for testing
  end

end
